In [1]:
import pandas as pd

In [2]:
import pandas as pd
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

phase1 = pd.read_csv('2-interim/phase1.csv')
phase2 = pd.read_csv('2-interim/phase2.csv')
phase3 = pd.read_csv('2-interim/phase3.csv')
phase4 = pd.read_csv('2-interim/phase4.csv')

C:\Users\wakib\AppData\Local\Temp\ipykernel_2540\1038553038.py:7: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  phase1 = pd.read_csv('interim/phase1.csv')
C:\Users\wakib\AppData\Local\Temp\ipykernel_2540\1038553038.py:10: DtypeWarning: Columns (1,86,87,88) have mixed types. Specify dtype option on import or set low_memory=False.
  phase4 = pd.read_csv('interim/phase4.csv')

In [3]:
# https://saturncloud.io/blog/how-to-select-date-range-from-pandas-dataframe/
date_ranges = [
    ('2020-05-11', '2020-05-12'),  # Phase 1, n = 6723
    ('2021-06-14', '2021-06-20'),  # Phase 2, n = 4592
    ('2022-05-13', '2022-05-30'),  # Phase 3, n = 3892
    ('2024-05-10', '2024-05-17')  # Phase 4, n = 2659
]

In [4]:
prefectures = [
    13,  # Tokyo 
    27,  # Osaka
    28,  # Hyogo
    40  # Fukuoka
]

In [5]:
expected_shapes = [
    6723,
    4592,
    3892,
    2659
]

In [6]:
# Prefecture columns and answer columns for each phase
prefecture_cols = ['1_PREFECTURE', '3_PREFECTURE', '5_PREFECTURE', '6_PREFECTURE']
answer_cols = ['1_ANSWERDATE', '3_ANSWERDATE', 'ANSWERDATE', '6_ANSWERDATE']

In [7]:
def verify_phase_data(phase, phase_num):
    # Convert to datetime format
    phase[answer_cols[phase_num]] = pd.to_datetime(phase[answer_cols[phase_num]]).dt.date
    phase[answer_cols[phase_num]] = pd.to_datetime(phase[answer_cols[phase_num]])
    
    start_date = date_ranges[phase_num][0]
    end_date = date_ranges[phase_num][1]

    # Check if dataframe is in the expected date range
    all_in_range = phase[answer_cols[phase_num]].between(start_date, end_date).all()
    
    # Check if dataframe has the expected number of entries
    phase_shape = phase.index.size == expected_shapes[phase_num]
    
    print(f"Phase {phase_num + 1}:\n"
          f"All dates in range ({date_ranges[phase_num]})? -> {all_in_range}\n"
          f"Expected shape ({expected_shapes[phase_num]})? -> {phase_shape}")

In [8]:
phase1_filtered = phase1[phase1['1_PREFECTURE'].isin(prefectures)]
phase1_filtered = phase1_filtered.dropna(subset=['1_ANSWERDATE'])
verify_phase_data(phase1_filtered, 0)
phase1_filtered.columns = phase1_filtered.columns.str.replace(r'^\d+_', '', regex=True).str.lower()
phase1_filtered

Phase 1:
All dates in range (('2020-05-11', '2020-05-12'))? -> True
Expected shape (6723)? -> True

,sampleid,answerdate,sex,age,ageid,prefecture,area,married,child,hincome,...,med_group,physical_group,mental_group,covid_group,k6_group3,k6_group2,phq9_%,phq9_item9,phq9_si,lsns_group
1,1759,2020-05-12,1.0,55.0,10.0,40.0,8.0,2.0,2.0,4.0,...,4.0,4.0,4.0,4.0,2.0,2.0,0.0,1.0,1.0,0.0
3,3474,2020-05-11,1.0,57.0,10.0,27.0,5.0,2.0,2.0,4.0,...,3.0,4.0,1.0,4.0,1.0,1.0,0.0,0.0,0.0,1.0
4,3793,2020-05-11,1.0,53.0,9.0,40.0,8.0,2.0,2.0,4.0,...,3.0,4.0,4.0,4.0,1.0,1.0,0.0,0.0,0.0,1.0
7,8488,2020-05-11,2.0,57.0,10.0,27.0,5.0,2.0,1.0,10.0,...,4.0,4.0,4.0,4.0,2.0,2.0,0.0,0.0,0.0,1.0
8,9703,2020-05-12,2.0,66.0,11.0,28.0,5.0,2.0,2.0,7.0,...,4.0,4.0,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11325,26523968,2020-05-11,2.0,49.0,8.0,28.0,5.0,2.0,1.0,10.0,...,4.0,4.0,4.0,4.0,1.0,1.0,0.0,0.0,0.0,1.0
11326,26524143,2020-05-12,2.0,19.0,2.0,13.0,3.0,1.0,1.0,3.0,...,4.0,4.0,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0
11328,26539614,2020-05-12,1.0,37.0,6.0,40.0,8.0,1.0,1.0,NaN,...,4.0,4.0,4.0,4.0,2.0,2.0,0.0,0.0,0.0,1.0
11331,26542309,2020-05-11,2.0,27.0,4.0,13.0,3.0,1.0,1.0,NaN,...,4.0,4.0,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0
11332,26543003,2020-05-12,2.0,18.0,2.0,13.0,3.0,1.0,1.0,NaN,...,4.0,4.0,4.0,4.0,1.0,1.0,0.0,0.0,0.0,1.0

In [9]:
# Export to CSV
phase1_filtered.to_csv("3-processed/phase1.csv", index=False)

In [10]:
phase2_filtered = phase2[phase2['3_PREFECTURE'].isin(prefectures)]
phase2_filtered = phase2[phase2['SAMPLEID'].isin(phase1_filtered['sampleid'])]
phase2_filtered = phase2_filtered.dropna(subset=['3_ANSWERDATE'])
verify_phase_data(phase2_filtered, 1)
phase2_filtered.columns = phase2_filtered.columns.str.replace(r'^\d+_', '', regex=True).str.lower()
phase2_filtered

Phase 2:
All dates in range (('2021-06-14', '2021-06-20'))? -> True
Expected shape (4592)? -> True

,sampleid,answerdate,sex,age,ageid,prefecture,area,married,child,hincome,...,mental_group,covid_group,k6_group3,k6_group2,phq9_%,gad_%,phq9_item9,phq9_si,audit_group,lsns_group
1,1759,2021-06-15,1.0,57.0,10.0,40.0,8.0,2.0,2.0,4.0,...,4.0,4.0,2.0,2.0,0.0,0.0,0.0,0.0,2.0,1.0
3,3474,2021-06-15,1.0,58.0,10.0,27.0,5.0,2.0,2.0,4.0,...,1.0,4.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0
4,3793,2021-06-14,1.0,54.0,9.0,40.0,8.0,2.0,2.0,4.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
7,8488,2021-06-15,2.0,59.0,10.0,27.0,5.0,2.0,1.0,10.0,...,4.0,4.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0
8,9703,2021-06-15,2.0,68.0,11.0,28.0,5.0,2.0,2.0,8.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11288,26520090,2021-06-14,2.0,30.0,5.0,13.0,3.0,1.0,1.0,4.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
11300,26521534,2021-06-15,1.0,43.0,7.0,13.0,3.0,2.0,2.0,4.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
11305,26521807,2021-06-14,1.0,60.0,11.0,28.0,5.0,2.0,1.0,3.0,...,4.0,4.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
11306,26521817,2021-06-18,1.0,30.0,5.0,28.0,5.0,2.0,2.0,4.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
11307,26522323,2021-06-16,2.0,52.0,9.0,13.0,3.0,2.0,2.0,1.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
# Export to CSV
phase2_filtered.to_csv("3-processed/phase2.csv", index=False)

In [12]:
phase3_filtered = phase3[phase3['5_PREFECTURE'].isin(prefectures)]
phase3_filtered = phase3[phase3['SAMPLEID'].isin(phase2_filtered['sampleid'])]
phase3_filtered = phase3_filtered.dropna(subset=['ANSWERDATE'])
verify_phase_data(phase3_filtered, 2)
phase3_filtered.columns = phase3_filtered.columns.str.replace(r'^\d+_', '', regex=True).str.lower()
phase3_filtered

Phase 3:
All dates in range (('2022-05-13', '2022-05-30'))? -> True
Expected shape (3892)? -> True

,sampleid,answerdate,sex,age,prefecture,married,child,hincome,pincome,job,...,mental_group,covid_group,k6_group3,k6_group2,phq9_%,gad_%,phq9_item9,phq9_si,lsns_group,audit_group
1,1759,2022-05-14,1.0,57.0,40.0,2.0,2.0,5.0,3.0,3.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3793,2022-05-14,1.0,55.0,40.0,2.0,2.0,4.0,3.0,4.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
7,8488,2022-05-13,2.0,59.0,27.0,2.0,1.0,10.0,1.0,8.0,...,4.0,4.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0
8,9703,2022-05-14,2.0,68.0,28.0,2.0,2.0,8.0,1.0,8.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10761,2022-05-14,1.0,53.0,27.0,1.0,1.0,2.0,2.0,5.0,...,4.0,4.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11285,26519682,2022-05-19,2.0,53.0,13.0,1.0,1.0,5.0,5.0,3.0,...,3.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11288,26520090,2022-05-13,2.0,31.0,13.0,1.0,1.0,3.0,3.0,3.0,...,2.0,4.0,2.0,2.0,1.0,0.0,1.0,1.0,1.0,0.0
11300,26521534,2022-05-16,1.0,44.0,13.0,2.0,2.0,5.0,4.0,3.0,...,4.0,3.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0
11305,26521807,2022-05-14,1.0,61.0,28.0,2.0,1.0,2.0,2.0,3.0,...,4.0,4.0,2.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0
11306,26521817,2022-05-13,1.0,31.0,28.0,2.0,2.0,4.0,3.0,1.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0

In [13]:
# Export to CSV
phase3_filtered.to_csv("3-processed/phase3.csv", index=False)

In [14]:
phase4_filtered = phase4[phase4['6_PREFECTURE'].isin(prefectures)]
phase4_filtered = phase4[phase4['SAMPLEID'].isin(phase3_filtered['sampleid'])]
phase4_filtered = phase4.dropna(subset=['6_ANSWERDATE'])
verify_phase_data(phase4_filtered, 3)
phase4_filtered.columns = phase4_filtered.columns.str.replace(r'^\d+_', '', regex=True).str.lower()
phase4_filtered

Phase 4:
All dates in range (('2024-05-10', '2024-05-17'))? -> True
Expected shape (2659)? -> True

C:\Users\wakib\AppData\Local\Temp\ipykernel_2540\2803151444.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phase[answer_cols[phase_num]] = pd.to_datetime(phase[answer_cols[phase_num]]).dt.date
C:\Users\wakib\AppData\Local\Temp\ipykernel_2540\2803151444.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phase[answer_cols[phase_num]] = pd.to_datetime(phase[answer_cols[phase_num]])

,sampleid,answerdate,sex,age,ageid,prefecture,area,married,child,hincome,...,mental_group,covid_group,k6_group3,k6_group2,phq9_%,gad_%,phq9_item9,phq9_si,lsns_group,audit_group
4,3793,2024-05-13,1.0,57.0,10.0,40.0,8.0,2.0,2.0,4.0,...,4.0,4.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0
8,9703,2024-05-14,2.0,70.0,11.0,28.0,5.0,2.0,2.0,7.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11,11532,2024-05-11,1.0,52.0,9.0,13.0,3.0,1.0,1.0,3.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
15,15778,2024-05-10,1.0,66.0,11.0,27.0,5.0,2.0,2.0,4.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
19,18713,2024-05-10,1.0,63.0,11.0,13.0,3.0,2.0,2.0,7.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11204,26475923,2024-05-11,1.0,57.0,10.0,27.0,5.0,2.0,2.0,2.0,...,4.0,4.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0
11208,26476814,2024-05-10,1.0,55.0,10.0,13.0,3.0,2.0,2.0,7.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
11209,26476898,2024-05-13,2.0,50.0,9.0,40.0,8.0,2.0,1.0,5.0,...,4.0,3.0,3.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0
11288,26520090,2024-05-10,2.0,33.0,5.0,13.0,3.0,1.0,1.0,4.0,...,3.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
11300,26521534,2024-05-15,1.0,46.0,8.0,13.0,3.0,2.0,2.0,4.0,...,4.0,4.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
# Export to CSV
phase4_filtered.to_csv("3-processed/phase4.csv", index=False)