# CS 198/199 
# Joaquin B. Salvador
# Explainable AI for Post-COVID Psychological Profile Prediction

## 2.3
### multiclass

In [1]:
# -------------------------------------
# Library configuration
# -------------------------------------
# Standard libraries
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
# -------------------------------------
# Settings
# -------------------------------------
random_state = 42

## Data preprocessing

In [3]:
# Loading dataset
df = pd.read_csv('data/data.csv')

In [4]:
# Displaying dataset
df

,SAMPLEID,ANSWERDATE,5_SEX,5_AGE,5_PREFECTURE,5_MARRIED,5_CHILD,5_HINCOME,5_PINCOME,5_JOB,...,5_AUDIT_group,6_K6_total,6_PHQ9_total,6_GAD7_total,6_SSS8_total,6_PTGI-X(Q7_22_27),6_SHS_total,6_UCLA_total,6_LSNS6_total,6_AUDIT
0,1106,2022/05/13-19:39:52,1.0,67.0,14.0,2.0,2.0,3.0,1.0,12.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1759,2022/05/14-08:44:24,1.0,57.0,40.0,2.0,2.0,5.0,3.0,3.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1916,2022/05/13-20:19:11,1.0,62.0,11.0,2.0,2.0,2.0,2.0,3.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3793,2022/05/14-18:23:23,1.0,55.0,40.0,2.0,2.0,4.0,3.0,4.0,...,0.0,12.0,15.0,14.0,18.0,19.0,4.0,24.0,4.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24045,30063086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24046,30081779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24047,30093317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24048,30094439,2022/05/13-21:35:19,2.0,34.0,28.0,2.0,1.0,10.0,1.0,8.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24049,30095042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Sorting dataset based on SAMPLEID
df_sorted = df.sort_values(by=['SAMPLEID'])

In [6]:
# Displaying sorted dataset
df_sorted

,SAMPLEID,ANSWERDATE,5_SEX,5_AGE,5_PREFECTURE,5_MARRIED,5_CHILD,5_HINCOME,5_PINCOME,5_JOB,...,5_AUDIT_group,6_K6_total,6_PHQ9_total,6_GAD7_total,6_SSS8_total,6_PTGI-X(Q7_22_27),6_SHS_total,6_UCLA_total,6_LSNS6_total,6_AUDIT
0,1106,2022/05/13-19:39:52,1.0,67.0,14.0,2.0,2.0,3.0,1.0,12.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16161,1171,2022/05/13-19:35:52,1.0,59.0,14.0,2.0,2.0,6.0,5.0,3.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16162,1263,2022/05/13-19:44:02,1.0,73.0,14.0,2.0,2.0,2.0,2.0,12.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14191,1346,2022/05/13-19:00:17,1.0,52.0,26.0,2.0,2.0,3.0,3.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18612,1398,2022/05/13-20:26:45,1.0,52.0,27.0,1.0,1.0,3.0,3.0,6.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17614,30094793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16160,30094932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24049,30095042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20047,30095074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13575,30095175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Dropping empty rows from sorted dataset
df_cleaned = df_sorted.dropna()

In [8]:
# Displaying cleaned dataset
df_cleaned

,SAMPLEID,ANSWERDATE,5_SEX,5_AGE,5_PREFECTURE,5_MARRIED,5_CHILD,5_HINCOME,5_PINCOME,5_JOB,...,5_AUDIT_group,6_K6_total,6_PHQ9_total,6_GAD7_total,6_SSS8_total,6_PTGI-X(Q7_22_27),6_SHS_total,6_UCLA_total,6_LSNS6_total,6_AUDIT
4,3793,2022/05/14-18:23:23,1.0,55.0,40.0,2.0,2.0,4.0,3.0,4.0,...,0.0,12.0,15.0,14.0,18.0,19.0,4.00,24.0,4.0,6.0
8,9703,2022/05/14-07:51:04,2.0,68.0,28.0,2.0,2.0,8.0,1.0,8.0,...,0.0,1.0,0.0,0.0,1.0,3.0,4.50,11.0,18.0,0.0
11,11532,2022/05/14-12:53:15,1.0,50.0,13.0,1.0,1.0,3.0,3.0,3.0,...,0.0,1.0,2.0,0.0,1.0,0.0,4.00,32.0,0.0,0.0
15,15778,2022/05/13-19:09:38,1.0,64.0,27.0,2.0,2.0,5.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,18.0,5.50,21.0,13.0,0.0
19,18713,2022/05/13-22:01:06,1.0,61.0,13.0,2.0,2.0,10.0,10.0,2.0,...,0.0,0.0,2.0,0.0,0.0,15.0,5.25,22.0,18.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11204,26475923,2022/05/15-01:24:36,1.0,55.0,27.0,1.0,2.0,2.0,2.0,3.0,...,0.0,12.0,4.0,7.0,13.0,18.0,4.00,25.0,6.0,6.0
11208,26476814,2022/05/13-19:35:37,1.0,53.0,13.0,2.0,2.0,7.0,7.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.00,25.0,0.0,0.0
11209,26476898,2022/05/13-21:36:28,2.0,48.0,40.0,2.0,1.0,5.0,1.0,8.0,...,0.0,13.0,6.0,0.0,5.0,12.0,3.75,26.0,4.0,0.0
11288,26520090,2022/05/13-19:39:54,2.0,31.0,13.0,1.0,1.0,3.0,3.0,3.0,...,0.0,2.0,3.0,2.0,14.0,12.0,4.00,27.0,3.0,0.0
11300,26521534,2022/05/16-06:27:12,1.0,44.0,13.0,2.0,2.0,5.0,4.0,3.0,...,0.0,6.0,1.0,0.0,8.0,0.0,4.00,27.0,14.0,4.0

In [9]:
# Gathering column names
column_names = df_cleaned.columns.tolist()

In [10]:
# Displaying column names
column_names

['SAMPLEID',
 'ANSWERDATE',
 '5_SEX',
 '5_AGE',
 '5_PREFECTURE',
 '5_MARRIED',
 '5_CHILD',
 '5_HINCOME',
 '5_PINCOME',
 '5_JOB',
 '5_STUDENT',
 '5_Number_fam',
 '5_SchoolGrade',
 '5_YearsEnrolled',
 '5_VacNum',
 '5_UkraineMoviePicture',
 '5_UkraineReadListen',
 '5_Med_self',
 '5_Medself_covid',
 '5_Med_fam',
 '5_Medfam_covid',
 '5_Current_physical',
 '5_Past_physical',
 '5_Current_mental',
 '5_Past_mental',
 '5_Current_covid19',
 '5_Past_covid19',
 '5_K6_total',
 '5_PHQ9_total',
 '5_GAD7_total',
 '5_SSS8_total',
 '5_PTGI-X(Q7_39_44)',
 '5_MAIA_1',
 '5_MAIA_2',
 '5_MAIA_3',
 '5_MAIA_4',
 '5_MAIA_5',
 '5_MAIA_6',
 '5_MAIA_7',
 '5_MAIA_8',
 '5_SHS_total',
 '5_UCLA_total',
 '5_LSNS6_total',
 '5_AUDIT',
 '5_Exercise',
 '5_HealthyDiet',
 '5_FavoriteActivity',
 '5_Interaction_offline',
 '5_Interaction_online',
 '5_PB_Continuous',
 '5_PB_Altruistic',
 '5_PB_Avoidant',
 '5_Trust_gov',
 '5_Trust_SM',
 '5_Vaccination_will',
 '5_PB_understanding',
 '5_Optimism',
 '5_HealthySleep',
 '5_DeteriorationEconomy',
 '5_DeteriorationInteract',
 '5_Frustration',
 '5_CovidAnxiety',
 '5_CovidSleepless',
 '5_DifficultyLiving',
 '5_DifficultyWork',
 '5_PTG1_S22',
 '5_PTG2_S23',
 '5_PTG3_S24',
 '5_PTG4_S25',
 '5_PTG5_S_26',
 '5_PTG6_S27',
 '5_Interest_Ukraine',
 '5_Support_Ukraine',
 '5_Support_Russia',
 '5_Age_group',
 '5_HINCOME_group',
 '5_JOB_group',
 '5_Med_group',
 '5_Med_covid_group',
 '5_Physical_group',
 '5_Mental_group',
 '5_Covid_group',
 '5_K6_group3',
 '5_K6_group2',
 '5_PHQ9_%',
 '5_GAD_%',
 '5_PHQ9_item9',
 '5_PHQ9_SI',
 '5_LSNS_group',
 '5_AUDIT_group',
 '6_K6_total',
 '6_PHQ9_total',
 '6_GAD7_total',
 '6_SSS8_total',
 '6_PTGI-X(Q7_22_27)',
 '6_SHS_total',
 '6_UCLA_total',
 '6_LSNS6_total',
 '6_AUDIT']

In [11]:
# Setting targets
df_targets = df_cleaned[['6_K6_total',
 '6_PHQ9_total',
 '6_GAD7_total',
 '6_SSS8_total',
 '6_PTGI-X(Q7_22_27)',
 '6_SHS_total',
 '6_UCLA_total',
 '6_LSNS6_total',
 '6_AUDIT']]

num_targets = len(df_targets.columns.tolist())

In [12]:
# Setting features
df_features = df_cleaned.drop([
 'SAMPLEID',
 'ANSWERDATE',
 '6_K6_total',
 '6_PHQ9_total',
 '6_GAD7_total',
 '6_SSS8_total',
 '6_PTGI-X(Q7_22_27)',
 '6_SHS_total',
 '6_UCLA_total',
 '6_LSNS6_total',
 '6_AUDIT'], axis=1)

num_features = len(df_features.columns.tolist())

In [13]:
df_features

,5_SEX,5_AGE,5_PREFECTURE,5_MARRIED,5_CHILD,5_HINCOME,5_PINCOME,5_JOB,5_STUDENT,5_Number_fam,...,5_Mental_group,5_Covid_group,5_K6_group3,5_K6_group2,5_PHQ9_%,5_GAD_%,5_PHQ9_item9,5_PHQ9_SI,5_LSNS_group,5_AUDIT_group
4,1.0,55.0,40.0,2.0,2.0,4.0,3.0,4.0,0.0,2.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
8,2.0,68.0,28.0,2.0,2.0,8.0,1.0,8.0,0.0,3.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
11,1.0,50.0,13.0,1.0,1.0,3.0,3.0,3.0,0.0,0.0,...,4.0,4.0,3.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0
15,1.0,64.0,27.0,2.0,2.0,5.0,3.0,3.0,0.0,4.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
19,1.0,61.0,13.0,2.0,2.0,10.0,10.0,2.0,0.0,1.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11204,1.0,55.0,27.0,1.0,2.0,2.0,2.0,3.0,0.0,3.0,...,4.0,4.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
11208,1.0,53.0,13.0,2.0,2.0,7.0,7.0,3.0,0.0,2.0,...,4.0,4.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,0.0
11209,2.0,48.0,40.0,2.0,1.0,5.0,1.0,8.0,0.0,1.0,...,4.0,4.0,3.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0
11288,2.0,31.0,13.0,1.0,1.0,3.0,3.0,3.0,0.0,0.0,...,2.0,4.0,2.0,2.0,1.0,0.0,1.0,1.0,1.0,0.0
11300,1.0,44.0,13.0,2.0,2.0,5.0,4.0,3.0,0.0,3.0,...,4.0,3.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0

In [14]:
# Feature scaling
# Used as reference: https://analyticsindiamag.com/ai-mysteries/a-beginners-guide-to-scikit-learns-mlpclassifier/
#for col in df_features.columns.tolist():
#    df_features[col] = LabelEncoder().fit_transform(df_features[col])

for col in df_targets.columns.tolist():
    df_targets[col] = LabelEncoder().fit_transform(df_targets[col])
    
print(df_targets)

       6_K6_total  6_PHQ9_total  6_GAD7_total  6_SSS8_total  \
4              12            15            14            18
8               1             0             0             1
11              1             2             0             1
15              0             0             0             0
19              0             2             0             0
...           ...           ...           ...           ...
11204          12             4             7            13
11208           0             0             0             0
11209          13             6             0             5
11288           2             3             2            14
11300           6             1             0             8

       6_PTGI-X(Q7_22_27)  6_SHS_total  6_UCLA_total  6_LSNS6_total  6_AUDIT
4                      19           12            14              4        6
8                       3           14             1             18        0
11                      0           12            22              0        0
15                     18           18            11             13        0
19                     15           17            12             18        0
...                   ...          ...           ...            ...      ...
11204                  18           12            15              6        6
11208                   0           12            15              0        0
11209                  12           11            16              4        0
11288                  12           12            17              3        0
11300                   0           12            17             14        4

[2659 rows x 9 columns]

C:\Users\wakib\AppData\Local\Temp\ipykernel_12684\4139783818.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_targets[col] = LabelEncoder().fit_transform(df_targets[col])
C:\Users\wakib\AppData\Local\Temp\ipykernel_12684\4139783818.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_targets[col] = LabelEncoder().fit_transform(df_targets[col])
C:\Users\wakib\AppData\Local\Temp\ipykernel_12684\4139783818.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_targets[col] = LabelEncoder().fit_transform(df_targets[col])
C:\Users\wakib\AppData\Local\Temp\ipykernel_12684\4139783818.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_targets[col] = LabelEncoder().fit_transform(df_targets[col])
C:\Users\wakib\AppData\Local\Temp\ipykernel_12684\4139783818.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_targets[col] = LabelEncoder().fit_transform(df_targets[col])
C:\Users\wakib\AppData\Local\Temp\ipykernel_12684\4139783818.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_targets[col] = LabelEncoder().fit_transform(df_targets[col])
C:\Users\wakib\AppData\Local\Temp\ipykernel_12684\4139783818.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_targets[col] = LabelEncoder().fit_transform(df_targets[col])
C:\Users\wakib\AppData\Local\Temp\ipykernel_12684\4139783818.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_targets[col] = LabelEncoder().fit_transform(df_targets[col])
C:\Users\wakib\AppData\Local\Temp\ipykernel_12684\4139783818.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_targets[col] = LabelEncoder().fit_transform(df_targets[col])

In [15]:
# Multilabel Binarizer
from sklearn.preprocessing import LabelBinarizer

target_names = df_targets.columns.tolist()
binary_targets = {}

for target in target_names:
 lb = LabelBinarizer()
 binary_targets[target] = lb.fit_transform(df_targets[target])
 print(f"{target}")
 print(binary_targets[target])

6_K6_total
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
6_PHQ9_total
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]
6_GAD7_total
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
6_SSS8_total
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
6_PTGI-X(Q7_22_27)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
6_SHS_total
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
6_UCLA_total
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
6_LSNS6_total
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
6_AUDIT
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [17]:
# Make target arrays based on the following ranges
# K6 - 0 to 24
# PHQ-9 - 0 to 27
# GAD-7 - O to 21
# SSS-8 - 0 to 32
# LSNS - 0 to 60
# UCLA - 0 to 80
# SHS - 1 to 7

binary_targets_df = pd.concat(
    [pd.DataFrame(binary_targets[target], columns=[f"{target}_{i}" for i in range(binary_targets[target].shape[1])]) 
     for target in binary_targets],
    axis=1
)

print(binary_targets_df)

      6_K6_total_0  6_K6_total_1  6_K6_total_2  6_K6_total_3  6_K6_total_4  \
0                0             0             0             0             0
1                0             1             0             0             0
2                0             1             0             0             0
3                1             0             0             0             0
4                1             0             0             0             0
...            ...           ...           ...           ...           ...
2654             0             0             0             0             0
2655             1             0             0             0             0
2656             0             0             0             0             0
2657             0             0             1             0             0
2658             0             0             0             0             0

      6_K6_total_5  6_K6_total_6  6_K6_total_7  6_K6_total_8  6_K6_total_9  \
0                0             0             0             0             0
1                0             0             0             0             0
2                0             0             0             0             0
3                0             0             0             0             0
4                0             0             0             0             0
...            ...           ...           ...           ...           ...
2654             0             0             0             0             0
2655             0             0             0             0             0
2656             0             0             0             0             0
2657             0             0             0             0             0
2658             0             1             0             0             0

      ...  6_AUDIT_26  6_AUDIT_27  6_AUDIT_28  6_AUDIT_29  6_AUDIT_30  \
0     ...           0           0           0           0           0
1     ...           0           0           0           0           0
2     ...           0           0           0           0           0
3     ...           0           0           0           0           0
4     ...           0           0           0           0           0
...   ...         ...         ...         ...         ...         ...
2654  ...           0           0           0           0           0
2655  ...           0           0           0           0           0
2656  ...           0           0           0           0           0
2657  ...           0           0           0           0           0
2658  ...           0           0           0           0           0

      6_AUDIT_31  6_AUDIT_32  6_AUDIT_33  6_AUDIT_34  6_AUDIT_35
0              0           0           0           0           0
1              0           0           0           0           0
2              0           0           0           0           0
3              0           0           0           0           0
4              0           0           0           0           0
...          ...         ...         ...         ...         ...
2654           0           0           0           0           0
2655           0           0           0           0           0
2656           0           0           0           0           0
2657           0           0           0           0           0
2658           0           0           0           0           0

[2659 rows x 266 columns]

# Building the model

We pivot to using scikit-learn because of the finicky nature of PyTorch

https://scikit-learn.org/dev/modules/generated/sklearn.neural_network.MLPClassifier.html

Since we see that the number of targets is greater than one and the cardinality is greater than two, we then know that we have a multiclass-multioutput problem

Reference: https://scikit-learn.org/1.5/modules/multiclass.html

In [18]:
# -------------------------------------
# Library configuration
# -------------------------------------
# Standard libraries
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [19]:
X = df_features
y = binary_targets_df

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=random_state)

In [25]:
clf = MLPClassifier(max_iter=5000, random_state=random_state).fit(X_train, y_train)

In [26]:
clf.predict_proba(X_test)

array([[5.17205878e-01, 9.28039120e-02, 8.62372974e-03, ...,
        9.29667119e-15, 5.35427978e-25, 2.17592472e-16],
       [9.55871108e-01, 2.68660627e-02, 3.10073740e-02, ...,
        3.86177729e-09, 1.07210746e-15, 1.46248304e-09],
       [9.83074092e-01, 1.11620109e-02, 3.70374185e-04, ...,
        2.44542691e-09, 1.72074358e-10, 3.25665999e-09],
       ...,
       [8.85711436e-01, 1.10098252e-01, 3.74338824e-02, ...,
        3.45098585e-11, 1.26288084e-13, 2.58034244e-13],
       [9.76192107e-01, 3.00320157e-02, 1.23145068e-02, ...,
        1.34846687e-16, 4.44652615e-27, 5.72694836e-19],
       [6.70415426e-01, 1.29558578e-01, 5.76843595e-02, ...,
        6.68966475e-09, 1.09434346e-10, 4.25530529e-10]])

In [27]:
clf.predict(X_test)

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [28]:
clf.score(X_test, y_test)

0.0

In [29]:
X_test

,5_SEX,5_AGE,5_PREFECTURE,5_MARRIED,5_CHILD,5_HINCOME,5_PINCOME,5_JOB,5_STUDENT,5_Number_fam,...,5_Mental_group,5_Covid_group,5_K6_group3,5_K6_group2,5_PHQ9_%,5_GAD_%,5_PHQ9_item9,5_PHQ9_SI,5_LSNS_group,5_AUDIT_group
2389,2.0,66.0,13.0,2.0,2.0,10.0,1.0,9.0,0.0,3.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
364,1.0,61.0,27.0,2.0,2.0,4.0,4.0,4.0,0.0,1.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4258,1.0,63.0,13.0,1.0,2.0,5.0,5.0,3.0,0.0,0.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4923,2.0,49.0,13.0,2.0,2.0,4.0,2.0,5.0,0.0,3.0,...,4.0,3.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0
1999,1.0,60.0,13.0,1.0,1.0,7.0,7.0,3.0,0.0,0.0,...,4.0,4.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6482,1.0,59.0,13.0,2.0,2.0,4.0,2.0,12.0,0.0,3.0,...,4.0,4.0,2.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0
3317,1.0,52.0,40.0,2.0,2.0,5.0,5.0,1.0,0.0,3.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
59,2.0,50.0,13.0,1.0,1.0,3.0,3.0,3.0,0.0,1.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1751,1.0,54.0,27.0,2.0,2.0,6.0,4.0,4.0,0.0,3.0,...,4.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1843,2.0,64.0,27.0,2.0,2.0,3.0,1.0,8.0,0.0,2.0,...,4.0,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [30]:
y_test

,6_K6_total_0,6_K6_total_1,6_K6_total_2,6_K6_total_3,6_K6_total_4,6_K6_total_5,6_K6_total_6,6_K6_total_7,6_K6_total_8,6_K6_total_9,...,6_AUDIT_26,6_AUDIT_27,6_AUDIT_28,6_AUDIT_29,6_AUDIT_30,6_AUDIT_31,6_AUDIT_32,6_AUDIT_33,6_AUDIT_34,6_AUDIT_35
831,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
124,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1431,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1613,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
700,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1146,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
613,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
643,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0